# Generated by Django 4.2.6 on 2024-01-21 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_alter_activity_type_type_name'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active_timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.timetable'),
        ),
    ]
