# Generated by Django 4.2.6 on 2023-12-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timetable_assignment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='teacher',
            field=models.ManyToManyField(to='timetable.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
