# Generated by Django 4.2.6 on 2024-01-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_remove_course_timetable_course_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_type',
            name='type_name',
            field=models.CharField(blank=True, default=models.CharField(default='def', max_length=100), max_length=100),
        ),
    ]
