# Generated by Django 4.2.6 on 2024-01-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_alter_activity_type_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
